---
# Available tags for broadcast messages, popups and titles:
# - {MAXPLAYERS}: Show maximum players by server 
# - {TOTALPLAYERS}: Show the number of all online players
# - {PREFIX}: Show prefix
# - {TIME}: Show current time
# - {TODAY}: Show current day and moth
# sendTitle
sendTitle: 
    enable: true 
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
                  #  [ Title,  SubTitle ]
        ["{PREFIX} &b1. This is message!", "{TIME}"],
        ["{PREFIX} &b2. This is message!", "{TIME}"],
        ["{PREFIX} &b3. This is message!", "{TIME}"]
    ]
# sendPopup
sendPopup: 
    enable: true
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
        "{TODAY} {PREFIX} &b1. This is message!",
        "{TODAY} {PREFIX} &b2. This is message!",
        "{TODAY} {PREFIX} &b3. This is message!"
    ]
# sendTips
sendTips: 
    enable: true
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
        "{TODAY} {PREFIX} &b1. This is message!",
        "{TODAY} {PREFIX} &b2. This is message!",
        "{TODAY} {PREFIX} &b3. This is message!"
    ]
# sendAlerts
sendAlerts: 
    enable: true
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
        "{TODAY} {PREFIX} &b1. This is message!",
        "{TODAY} {PREFIX} &b2. This is message!",
        "{TODAY} {PREFIX} &b3. This is message!"
    ]
...